export default {
    EFFICIENCY_THRESHOLD: 0.05,
    EXPOSURE_FACTOR: 0.3,
    STOP_LOSS_PARAMETER: 1.25,
    SYSTEM_LEVERAGE_BUY: 2,
    SYSTEM_LEVERAGE_SELL: 3,
    SYSTEM_OVERLOAD: false,
    IS_USER_INTERFERE : false,
    LIMIT_ORDER_DISTANCE: 0.17,
    LIMIT_ORDER_SIZE_WEIGHT: 0.20,
    BITMEX_SPREAD: 10
}

